import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from 'next/image';
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <header className="w-full bg-transparent">
          <div className="max-w-6xl mx-auto px-4 py-3">
            <Link href="/" className="inline-flex items-center gap-3">
              <Image
                src="/XFoundry Logo.jpeg"
                alt="Home"
                width={48}
                height={48}
                className="rounded-full"
              />
              <span className="text-sm font-medium text-black dark:text-zinc-50">Home</span>
            </Link>
          </div>
        </header>

        <main className="pt-4">{children}</main>
      </body>
    </html>
  );
}
